# Generated by Django 3.2.3 on 2021-05-20 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_alter_adminprofile_user'),
        ('members', '0004_alter_memberprofile_member_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('loan_passed', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_amount', models.IntegerField(max_length=200)),
                ('loan_period', models.DateTimeField(default=django.utils.timezone.now)),
                ('Loan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily')], default='MONTHLY', max_length=9)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adminprofile')),
                ('loan_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberarea')),
                ('member_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberprofile')),
            ],
        ),
    ]
