# Generated by Django 3.2.3 on 2021-05-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_loancollentionsheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='approved_by',
            new_name='loan_approved_by',
        ),
    ]
