# Generated by Django 3.2.3 on 2021-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20210521_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancollentionsheet',
            name='member',
            field=models.CharField(max_length=500),
        ),
    ]
