# Generated by Django 3.2.3 on 2021-05-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memberarea',
            fields=[
                ('area_id', models.IntegerField(default=1999, editable=False, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=200)),
            ],
        ),
    ]
