# Generated by Django 3.2.3 on 2021-05-20 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberprofile',
            fields=[
                ('member_no', models.IntegerField(default=0, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=500)),
                ('member_phone_number', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(regex='/(^(\\+88|0088)?(01){1}[3456789]{1}(\\d){8})$/')])),
                ('member_nid', models.IntegerField(max_length=16)),
                ('member_image', models.ImageField(default='member_icon.png', upload_to='members-profile-pictures')),
                ('member_mother_name', models.CharField(max_length=500)),
                ('member_father_name', models.CharField(max_length=500)),
                ('member_spouse_name', models.CharField(max_length=500)),
                ('nominee', models.CharField(max_length=500)),
                ('present_address', models.CharField(max_length=500)),
                ('present_city', models.CharField(blank=True, max_length=50, null=True)),
                ('present_village', models.CharField(blank=True, max_length=50, null=True)),
                ('present_union', models.CharField(blank=True, max_length=50, null=True)),
                ('present_word', models.CharField(blank=True, max_length=50, null=True)),
                ('present_thana', models.CharField(blank=True, max_length=50, null=True)),
                ('present_district', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_address', models.CharField(max_length=500)),
                ('permanent_city', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_village', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_union', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_word', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_thana', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=50, null=True)),
                ('member_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberarea')),
            ],
        ),
    ]
