# Generated by Django 3.2.3 on 2021-05-20 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='member_phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(regex='(^([+]{1}[8]{2}|0088)?(01){1}[3-9]{1}\\d{8})$')]),
        ),
    ]
