# Generated by Django 3.2.3 on 2021-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_memberprofile_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='member_nid',
            field=models.PositiveBigIntegerField(max_length=17),
        ),
    ]
